# DQN CONFIGURATION

cartpole1:
  env_id: "CartPole-v1"
  learning_rate: 0.001
  buffer_size: 100_000
  learning_starts: 1000
  batch_size: 32
  gamma: 0.99
  train_freq: 4
  target_update_interval: 250
  exploration_fraction: 0.1
  exploration_final_eps: 0.02
  verbose: 0
  total_timesteps: 200_000
  network_layers: [64, 64]
  network_activation: "ReLU"

cartpole2:
  env_id: "CartPole-v1"
  learning_rate: 0.001
  buffer_size: 100_000
  learning_starts: 1000
  batch_size: 32
  gamma: 0.99
  train_freq: 4
  target_update_interval: 1000
  exploration_fraction: 0.1
  exploration_final_eps: 0.02
  verbose: 0
  total_timesteps: 300_000
  network_layers: [10]
  network_activation: "ReLU"

# was successful, created DQN7
car1:
  env_id: "MountainCar-v0"
  learning_rate: 0.001
  buffer_size: 100_000
  learning_starts: 1000
  batch_size: 32
  gamma: 0.99
  train_freq: 4
  target_update_interval: 2000
  exploration_fraction: 0.3
  exploration_final_eps: 0.02
  verbose: 0
  total_timesteps: 2_000_000
  network_layers: [64,64]
  network_activation: "ReLU"

# created DQN8, Training time: 11810.78 seconds
car2:
  env_id: "MountainCar-v0"
  learning_rate: 0.001
  buffer_size: 100_000
  learning_starts: 1000
  batch_size: 64
  gamma: 0.99
  train_freq: 1
  target_update_interval: 1000
  exploration_fraction: 0.3
  exploration_final_eps: 0.05
  verbose: 0
  total_timesteps: 5_000_000
  network_layers: [64,64]
  network_activation: "ReLU"

# TBD created DQN9, Training time: 12130.84 seconds
flappybird1:
  env_id: "flappybird"
  learning_rate: 0.0005
  buffer_size: 100_000
  learning_starts: 3000
  batch_size: 64
  gamma: 0.99
  train_freq: 1
  target_update_interval: 1000
  exploration_fraction: 0.3
  exploration_final_eps: 0.05
  verbose: 0
  total_timesteps: 5_000_000
  network_layers: [256,256]
  network_activation: "ReLU"